---
title: "Indiscriminate Violence and Insurgency"
output: pdf_document
---

In this exercise, we analyze the relationship between indiscriminate
violence and insurgent attacks using data about Russian artillery fire
in Chechnya from 2000 to 2005.

This exercise is based on: Lyall, J. 2009. “[Does Indiscriminate Violence
Incite Insurgent Attacks?: Evidence from
Chechnya.](http://dx.doi.org/10.1177/0022002708330881)”
 *Journal of Conflict Resolution* 53(3): 331–62.

Some believe that
indiscriminate violence increases insurgent attacks by creating more
cooperative relationships between citizens and insurgents.  Others
believe that indiscriminate violence can be effective in suppressing
insurgent activities.  

This dataset was constructed around 159 events in which Russian
artillery shelled a village.  For each such event we record
the village where the shelling took place and whether it was in Groznyy,
how many people were killed, and the number of
insurgent attacks 90 days before and 90 days after the date of the event.
We then augment this data by observing the same information
for a set of demographically and geographically
similar villages that were not shelled during the same time periods.

The names and
descriptions of variables in the data file `chechen.csv` are

--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `village`            Name of village

 `groznyy`            Variable indicating whether a village is in
                      Groznyy (1) or not (0)

 `fire`               Whether Russians struck a village with artillery fire
                      (1) or not (0)

 `deaths`             Estimated number of individuals killed during Russian artillery fire
                      or NA if not fired on

 `preattack`          The number of insurgent attacks in the 90 days before being fired on

 `postattack`         The number of insurgent attacks in the 90 days after being fired on
--------------------------------------------------------------------------------

Note that the same village may
appear in the dataset several times as shelled and/or not shelled
because Russian attacks occurred at different times and locations.

## Question 1

How many villages were shelled by Russians?  How many were not?


## Question 2: Data Inspection - Mean and Median

Were artillery attacks on Grozny more lethal than attacks on villages outside of Grozny?  
Conduct the comparison in terms of the mean and median.

Use `tapply()` to compute the mean and median.
Store the result to an matrix object named `death_summary`
so that the first becomes the means and the second row becomes the median.
Finally, use the `knitr::kable()` function to create a nice-looking table, including some informative column names.
Briefly comment on the whether you think there is any difference between two types of villages.

  
  
## Question 3: Data Inspection - Quartiles and Quantiles

Compute the quartiles of the distribution of deaths in villages that were attacked by Russian artillery attacks inside and outside of Grozny and interpret their values. 

Afterwards, calculate the 5th and 95th quantiles for the overall fatalities of Russian artillery attacks, as well as the interquartile range.


### Question 4: Data Inspection - Variance and Standard Deviation

Calculate the variance and standard deviation of people killed by Russian artillery fire attacks in villages in Grozny and outside of Grozny. What do these measures tell us about differences in attacks between regions?


## Question 5: Average Treatment Effect

Compare the average number of insurgent attacks for observations
describing a shelled village and the others.
Compute the average treatment effect and store the result to an object named `ate`.
Report the value of `ate` and discuss whether you conclude that indiscriminate
violence reduces insurgent attacks.

### Conceptual Question: what might be the problem with using just this comparison to infer the causal effect of indiscriminate violence?


## Question 6: Covariate Balance

Considering only the pre-shelling periods, what is the difference between the average number of insurgent attacks for observations describing 
a shelled village and observations that do not? What does this suggest to you about the validity of comparison used for the previous question?


## Question 7

Create a new variable called `diffattack` by calculating
  the difference in the number of insurgent attacks in the before
  and after periods.  Among observations describing villages that were shelled
  did the number of insurgent attacks increase after being fired on?  
  Give a substantive interpretation of the result.
  


## Question 8

Compute the mean difference in the `diffattack` variable
  between observations where villages were shelled and those where
  they were not.   
  
  Does this analysis support the claim that indiscriminate violence reduces
  insurgency attacks?  Is the validity of this analysis improved over
  the analyses you conducted in the previous questions?  Why or why
  not?  Specifically, explain what additional factor this analysis
  addresses when compared to the analyses conducted in the previous
  questions.
  
